# Generated by Django 5.1 on 2024-08-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'number')},
        ),
    ]
