# Generated by Django 5.1 on 2024-09-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
